// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx1goA2aATPqqqW3LRFnW2y0qvF9SEhkI',
    appId: '1:945263688927:web:a1078888adb5e8635c3d6a',
    messagingSenderId: '945263688927',
    projectId: 'fir-auth-f2d60',
    authDomain: 'fir-auth-f2d60.firebaseapp.com',
    storageBucket: 'fir-auth-f2d60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQbHTr-XrNIdPB07p-jOpH5nJrVjFK9YE',
    appId: '1:945263688927:android:05aefedb49a8767a5c3d6a',
    messagingSenderId: '945263688927',
    projectId: 'fir-auth-f2d60',
    storageBucket: 'fir-auth-f2d60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXtXGbFCP2x3mx-tKi36MAcpWfIBreQbg',
    appId: '1:945263688927:ios:15343e145e0620be5c3d6a',
    messagingSenderId: '945263688927',
    projectId: 'fir-auth-f2d60',
    storageBucket: 'fir-auth-f2d60.appspot.com',
    iosBundleId: 'com.example.authtutorial',
  );
}
